### ISSUE TITLE
Quotes at the end of a line not handled correctly

### ISSUE THREAD

**Issue by TiGz** [titorenko/quick-csv-streamer#3]
Hi there,

First of all thanks for this project, it looks good. I have been trying to use it to parse some CSV files but I am having some issues when the last column is quoted.

If you add quotes to the cities-with-header.txt fixture like this:

    Country,City,AccentCity,Region,Population,Latitude,Longitude
    ad,andorra,Andorra,07,,"42.5","1.5166667"
    gb,city of london,City of London,H9,,"51.514125","-.093689"
    ua,kharkiv,Kharkiv,07,,"49.980814","36.252718"

Then the associated tests fail. I think the line break is missed and we don't skip to the next item correctly. This matches the behaviour I am seeing where only a subset of the items get parsed.

**Comment by titorenko** [comment]
Hi TiGz,
thanks for the issue report. It is now fixed in 0.2.2

**Comment by TiGz** [comment]
Cool - nice one!
