### ISSUE TITLE
Different use case

### ISSUE THREAD

**Issue by mdewilde** [titorenko/quick-csv-streamer#4]
I'm interested in testing your library (currently using Apache commons-csv). 
My use case is database imports.
The eventual domain model needs information combined from multiple different CSV files, so there are no models that map 1:1 with any of the imported CSV files.
Currently, I'm mapping from CSV straight to a database insert map.
My need seems to be a stream of raw CSV records, that will be consumed in database insert batches.
Is this something you may consider adding?

**Comment by titorenko** [comment]
This use case is fully supported.
